### ISSUE TITLE
not enough arguments in call to btcBot.Predict

### ISSUE THREAD

**Issue by essto** [FrappaF/TradeInGo#2]
Hi, 
I tried to run your code, but either in test mode:

```
go run . test
backtest/backtest.go:29:18: not enough arguments in call to btcBot.Predict
	have (data.Candle)
	want (data.Candle, time.Time)
```

or live mode

```
go run . live
backtest/backtest.go:29:18: not enough arguments in call to btcBot.Predict
	have (data.Candle)
	want (data.Candle, time.Time)
```

had the same issue.

I made a quick fix then:
```
diff --git a/backtest/backtest.go b/backtest/backtest.go
index eb7632b..7550545 100644
--- a/backtest/backtest.go
+++ b/backtest/backtest.go
@@ -26,7 +26,7 @@ func RunBacktest(from, to int64, resolution string) {
                t := res.GetT()[i]

                candle := data.Candle{Open: o, Close: c, High: h, Low: l, Volume: v, Timestamp: t}
-               btcBot.Predict(candle)
+               btcBot.Predict(candle, time.Time{})

        }
 }
 ```
 And it works in live mode, in test still doesn't work, but I faced another issue:
 ```
go run . test
panic: 401 Unauthorized

goroutine 1 [running]:
github.com/frappaf/tradingBot/backtest.RunBacktest(0x4?, 0x9554524fe92b1eaf?, {0x1404283, 0x2})
	/Users/essto/projects/TradeInGo/backtest/backtest.go:15 +0x348
main.main()
	/Users/essto/projects/TradeInGo/main.go:31 +0x230
exit status 2
``` 
I wonder why?

In live mode works, with some errors:
```
============================== *BOT STATUS* ====================================
Current balance: 10000.000000
Current position: NEUTRAL

CurrentArea:
Open: 0.000000	Close: 0.000000
High: 0.000000	Low: 0.000000
Volume: 0.000000	Timestamp: 0


Current daily candle:
Open: 19140.630859	Close: 0.000000
High: 19142.560547	Low: 19140.869141
Volume: 0.000000	Timestamp: 1665921350

=====================================°============================================

============================== *CURRENT PRICE* ====================================
Open: 19140.869141	Close: 19140.869141
High: 19140.869141	Low: 19140.869141
Volume: 0.000000	Timestamp: 1665921354

=====================================°============================================

2022/10/16 13:55:54 [ERROR] EventEmitter: panic in event handler: runtime error: index out of range [0] with length 0
goroutine 32 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.19.2/libexec/src/runtime/debug/stack.go:24 +0x65
github.com/ably/ably-go/ably.safeHandle.func1()
	/Users/essto/go/pkg/mod/github.com/ably/ably-go@v1.2.8/ably/event_emitter.go:78 +0x58
panic({0x13df640, 0xc000320048})
	/usr/local/Cellar/go/1.19.2/libexec/src/runtime/panic.go:884 +0x212
github.com/frappaf/tradingBot/bot.binarySearchForCandles({0x0?, 0x1?, 0x1?}, {0x469589bd, 0x469589bd, 0x469589bd, 0x469589bd, 0x0, 0x634bf14a}, 0x138be20?, ...)
	/Users/essto/projects/TradeInGo/bot/bot.go:81 +0x16e
github.com/frappaf/tradingBot/bot.(*Bot).findArea(0xc0001961c0, {0x469589bd, 0x469589bd, 0x469589bd, 0x469589bd, 0x0, 0x634bf14a})
	/Users/essto/projects/TradeInGo/bot/bot.go:65 +0xac
github.com/frappaf/tradingBot/bot.(*Bot).Predict(0xc0001961c0, {0x469589bd, 0x469589bd, 0x469589bd, 0x469589bd, 0x0, 0x634bf14a}, {0x9?, 0x0?, 0x16e9680?})
	/Users/essto/projects/TradeInGo/bot/bot.go:156 +0x592
github.com/frappaf/tradingBot/bot.(*Bot).Run.func1(0x9?)
	/Users/essto/projects/TradeInGo/bot/bot.go:303 +0x13a
github.com/ably/ably-go/ably.(*RealtimeChannel).SubscribeAll.func1({0x14b4260?, 0xc00017e800?})
	/Users/essto/go/pkg/mod/github.com/ably/ably-go@v1.2.8/ably/realtime_channel.go:459 +0x36
github.com/ably/ably-go/ably.safeHandle({0x14b4260?, 0xc00017e800?}, 0xc0001d2d20?, {{0x14b4de0?, 0xc0000c2378?}})
	/Users/essto/go/pkg/mod/github.com/ably/ably-go@v1.2.8/ably/event_emitter.go:81 +0x79
github.com/ably/ably-go/ably.(*eventListener).handle.func1()
	/Users/essto/go/pkg/mod/github.com/ably/ably-go@v1.2.8/ably/event_emitter.go:62 +0xe9
created by github.com/ably/ably-go/ably.(*eventListener).handle
	/Users/essto/go/pkg/mod/github.com/ably/ably-go@v1.2.8/ably/event_emitter.go:55 +0x1ee
^Csignal: interrupt
```
I don't know why?

By the way, thnx for the excellent project, and clean code.

**Comment by essto** [comment]
I have changed TOKEN as you pointed out in https://github.com/FrappaF/TradeInGo/issues/1 and it still has the same issue.

**Comment by FrappaF** [comment]
Fixed the error! I forgot to update the `backtest.go` file :)

You can get a free token at finnhub.io

Anyway thanks ;)
